version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - tiksn
    assignees:
      - tiksn
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    reviewers:
      - tiksn
    assignees:
      - tiksn
